name: AdvancedKitsChestPMMP
main: AdvancedKits\Main
version: 1.0.0
api: [3.0.0, 3.2.4]
author: ProxyTechDevs
softdepend: [""]
commands:
 kit:
  description: "This Plugin Is By @ProxyTechDevs On Twitter"
  usage: "/kit <KitName>"
  aliases: [kits]
  permission: advancedkits.command
permissions:
 advancedkits.command:
  description: "Allows The User To Do Use The /kit Command"
  default: true
